steps:

  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "***********************"
        echo "$_BRANCH_NAME"
        echo "***********************"
timeout: 2400s
  # [END tf-apply]